### ISSUE TITLE
实现水平垂直居中的N种方式

### ISSUE THREAD

**Issue by DamomHd** [Darren-supreme/interview-question#21]
```html
<div class="container">
  <div class="content"></div>
</div>
```

```css
.container{
      width:500px;
      height:500px;
      background-color:#999;
}
.content{
     width:200px;
     height:200px;
     background-color:#333;
}
```

**Comment by DamomHd** [comment]
### absolute + margin

```css
.container{
  position:relative;
}
.content{
  position: absolute;
  top: 0;
  bottom:0;
  right:0;
  left: 0;
  margin:auto;
}
```

**Comment by DamomHd** [comment]
### absolute + transform
```css
.container {
    position: relative;
}
.content {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
```

**Comment by DamomHd** [comment]
### flex

```css
.container {
    display: flex;
    justify-content: center;
    align-items: center;
}
.content {
    text-align: center;
}
```

**Comment by DamomHd** [comment]
### grid

```css
.container {
    display: grid;
    justify-items: center;
    align-items: center;
}
.content {
    text-align: center;
}
```

**Comment by DamomHd** [comment]
### css-table
```css
.container {
    display: table-cell;
    text-align: center;
    vertical-align: middle;
}
.content{
    display: inline-block;
}
```
